services:
  nginxproxymanager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    hostname: ngnixpm.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
    - ${BASE_PATH}/nginx:/data
    - ${BASE_PATH}/nginx/letsencrypt:/etc/letsencrypt
    restart: always 